//! Embedded license attribution.
//!
//! MIT/BSD (and most other) licenses require the full license text and
//! copyright notice of each dependency to be distributed with the binary. The
//! dependency licenses are collected by the `cratelist` tool into
//! `DEPENDENCIES_LICENSE` (regenerated by `.github/workflows/update_licenses.yml`
//! whenever `Cargo.lock` changes) and committed gzipped. We embed the compressed
//! file and decompress on demand, so the attribution travels inside the binary
//! without bloating it with ~3 MB of raw text.
//!
//! Exposed two ways: the desktop `--licenses` CLI flag ([`print_to_stdout`]) and
//! the in-app About / Licenses window (see `app.rs`), which is the only surface
//! available on Android.

use std::io::Read;
use std::sync::OnceLock;

/// This application's own license.
pub const MAIN_LICENSE: &str = include_str!("../license.txt");

/// Gzipped dependency license text, embedded at compile time.
const DEPS_GZ: &[u8] = include_bytes!("../DEPENDENCIES_LICENSE.gz");

/// The decompressed dependency license text, decompressed once on first use.
pub fn dependency_licenses() -> &'static str {
    static TEXT: OnceLock<String> = OnceLock::new();
    TEXT.get_or_init(|| {
        let mut decoder = flate2::read::GzDecoder::new(DEPS_GZ);
        let mut s = String::new();
        match decoder.read_to_string(&mut s) {
            Ok(_) => s,
            Err(e) => format!("Error decompressing embedded dependency licenses: {e}"),
        }
    })
    .as_str()
}

/// The dependency license text split into lines, cached for lazy GUI rendering
/// (so the window can draw only the visible rows of a very long document).
pub fn dependency_license_lines() -> &'static [String] {
    static LINES: OnceLock<Vec<String>> = OnceLock::new();
    LINES
        .get_or_init(|| dependency_licenses().lines().map(str::to_owned).collect())
        .as_slice()
}

/// Print this application's license followed by all dependency licenses to
/// stdout. Backs the `--licenses` command-line flag.
pub fn print_to_stdout() {
    println!("--- Housing Planner license ---\n");
    println!("{MAIN_LICENSE}");
    println!("\n--- Third-party dependency licenses ---\n");
    println!("{}", dependency_licenses());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_dependency_licenses_decompress() {
        let text = dependency_licenses();
        // Sanity: decompresses to real content covering our key dependencies.
        assert!(text.len() > 10_000);
        assert!(text.contains("egui"));
        assert!(text.contains("eframe"));
        assert!(!dependency_license_lines().is_empty());
    }
}
